version: '3.4'
services:
  agarwood:
    image: agarwood/user:2.0
    command: ['php', '/var/www/agarwood/bin/agarwood', 'http:start']
    container_name: agarwood-user
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    env_file:
      - .env
    ports:
      - ${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}
      - ${RPC_SERVER_PORT}:${RPC_SERVER_PORT}
